### ISSUE TITLE
Follow-up to https://github.com/FuelLabs/fuel-subgraph/pull/8

### ISSUE THREAD

**Issue by DiForss** [FuelLabs/fuel-subgraph#14]
More options for e.g. pulling old data
Better error handling, e.g. attempting to reconnect on network errors
Automated tests
CI checks
Batch requests, see https://github.com/FuelLabs/fuel-subgraph/pull/8#discussion_r1499045021

**Comment by Salka1988** [comment]
https://github.com/FuelLabs/fuel-subgraph/issues/11
