### ISSUE TITLE
Fix docker infinity memory expansion issue

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuel-subgraph#22]
Currently when running the docker of the subgraph the memory keeps growing until it crashes. We should identify and fix this issue to allow users to use the docker image without issues.

**Comment by deekerno** [comment]
So far, @Salka1988 and I identified a command flag -- `merger-prune-forked-blocks-after` -- on the `merger` component for Firehose that seems to fix this for now. Its default value is 50,000; this means that fifty thousand individual block files are produced before they're merged into a file containing all of the aforementioned blocks. We've set this to a more reasonable value and we'll continue to investigate any other sources for unexpected memory expansion.
