### ISSUE TITLE
Prepare PR to the graph-node tooling repository to merge fuel support

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuel-subgraph#26]
To allow for subgraphs to be developed using Fuel networks, the AssemblyScript library (`graph-ts`) must add support for Fuel types and the CLI (`graph-cli`) must add the names of Graph networks.

Information and examples are included at the bottom of the “Add Chain” document:
https://github.com/graphprotocol/graph-node/blob/master/docs/implementation/add-chain.md#user-content-what-else

**Comment by Salka1988** [comment]
https://github.com/graphprotocol/graph-node/pull/5340#issuecomment-2052125879
