### ISSUE TITLE
Make PR for graph-node to include support for fuel 

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuel-subgraph#27]
Make PR on [graph-node ](https://github.com/graphprotocol/graph-node) repository.

**Comment by Salka1988** [comment]
PR opened at: https://github.com/graphprotocol/graph-node/pull/5340

**Comment by Salka1988** [comment]
https://github.com/graphprotocol/graph-node/pull/5340#issuecomment-2052125879
